version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.3
    steps:
      - checkout
      - run:
          name: Pre Test Clean
          command: lein clean
      - run:
          name: Test
          command: lein test